### ISSUE TITLE
执行 npm i 报错，node 版本: v12.6.0

### ISSUE THREAD

**Issue by qihuan92** [PEDx/BannerMan#2]
大佬，当执行 `npm i` 时，报如下错误，node 版本: v12.6.0
```
> npm run theme


> banner-man@1.0.0 theme /Users/qi/project-web/BannerMan
> et

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/qi/project-web/BannerMan/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/qi/project-web/BannerMan/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/qi/project-web/BannerMan/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! banner-man@1.0.0 theme: `et`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the banner-man@1.0.0 theme script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qi/.npm/_logs/2019-07-17T00_37_01_221Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! banner-man@1.0.0 postinstall: `npm run theme`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the banner-man@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qi/.npm/_logs/2019-07-17T00_37_01_285Z-debug.log
```

**Comment by PEDx** [comment]
@qihuan92 欢哥，node 降到 11 以下试试。。。  
https://github.com/mafintosh/prebuildify-ci/issues/5
https://github.com/gulpjs/gulp/issues/2324

**Comment by qihuan92** [comment]
> @qihuan92 欢哥，node 降到 11 以下试试。。。
> [mafintosh/prebuildify-ci#5](https://github.com/mafintosh/prebuildify-ci/issues/5)
> [gulpjs/gulp#2324](https://github.com/gulpjs/gulp/issues/2324)

好的~😝
